### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by legalsylvain** [grap/grap-odoo-business#149]
blabl
- [x] recurring_consignment - By @legalsylvain - #144
- [x] recurring_consignment_pos - By @legalsylvain - #145
- [ ] recurring_consignment_purchase - By @legalsylvain - #146
- [ ] recurring_consignment_sale - By @legalsylvain - #147
- [ ] recurring_consignment_test - By @legalsylvain - #148
- [x] technical_partner_access - By @legalsylvain - #150
